Repository master-csmi/csmi-stages-2025, pull requests merged in 2025-08, with the labels that each got.

#8 Ajout du rapport Vivant Rodolphe
  modules/m1/attachments/Vivant-Rodolphe.pdf
Labels: M1, Soutenances, Stages

#6 Ajout du rapport Dieng Adama
  modules/m2/attachments/Dieng-Adama-slides.pdf
  modules/m2/attachments/Dieng-Adama.pdf
Labels: M2, Soutenances, Stages

#4 Ajout rapport et slides Zaouache Narimane
  modules/m1/attachments/Zaouache-Narimane-slides.pdf
  modules/m1/attachments/Zaouache-Narimane.pdf
Labels: Soutenances, Stages

#1 Ajout du rapport et des slides Roth
  modules/m2/attachments/Roth-Robin-slides.pdf
  modules/m2/attachments/Roth-Robin.pdf
Labels: M2, Soutenances, Stages

#24 update slides and report
  modules/m2/attachments/Bouhenniche-Oussama-slides.pdf
  modules/m2/attachments/Bouhenniche-Oussama.pdf
Labels: M2, Soutenances, Stages

#36 M2 senger
  modules/m2/attachments/Senger-Pierre-Antoine-slides.pdf
  modules/m2/attachments/Senger-Pierre-Antoine.pdf
Labels: M2, Soutenances, Stages

#40 M2 wade
  modules/m2/attachments/Wade-Abdou-slides.pdf
  modules/m2/attachments/Wade-Abdou.pdf
Labels: M2, Soutenances, Stages

#33 Adding link
  modules/m2/partials/rapports.adoc
  modules/m2/partials/stages.adoc
Labels: M2, Soutenances, Stages

#43 Ajout du rapport Wade Abdou
  modules/m2/attachments/Wade-Abdou.pdf
Labels: M2, Soutenances, Stages
